/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package net.corda.quasar.hello

import org.junit.jupiter.api.Test

class AppTest {

    @Test
    fun test() {
        println("")
    }
}
